# Generated by Django 5.2.14 on 2026-06-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1231_duckgresserverteam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changerequest",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("valid", "Valid"),
                    ("invalid", "Invalid"),
                    ("stale", "Stale (resource changed)"),
                ],
                default="valid",
                max_length=16,
            ),
        ),
    ]
