# Generated by Django 5.2.14 on 2026-06-22 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feature_flags", "0003_evaluationcontext_hidden_from_suggestions"),
        ("posthog", "1231_duckgresserverteam"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledchange",
            name="change_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_changes",
                to="posthog.changerequest",
            ),
        ),
    ]
